apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-product-pvc
  namespace: microservices-siti
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product
  namespace: microservices-siti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-product
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-product
    spec:
      containers:
        - name: mysql-product
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "productdb"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - name: mysql-product-storage
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: mysql-product-storage
          persistentVolumeClaim:
            claimName: mysql-product-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-product
  namespace: microservices-siti
spec:
  selector:
    app: mysql-product
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
